### ISSUE TITLE
Dependency `go/splaytree` is no longer available. Suggest vendoring dependencies

### ISSUE THREAD

**Issue by nii236** [kierdavis/argo#4]
Hi there!

Running 
```
go get github.com/kierdavis/argo
```
Does not work, as the following error is returned when you try to build the package.
```
go build
rdfz.go:6:2: cannot find package "github.com/kierdavis/go/splaytree" in any of:
	/usr/local/go/src/github.com/kierdavis/go/splaytree (from $GOROOT)
	/Users/nii236/Go/src/github.com/kierdavis/go/splaytree (from $GOPATH)
```

It turns out this is one of your older repos that no longer exist on your account.

**Comment by kierdavis** [comment]
Hi,

I'm not surprised that this doesn't compile anymore, since I haven't maintained this project for four years.

I've pushed some commits that should fix the compile errors but I don't guarantee that the code will work effectively. I would recommend using something more up-to-date like [github.com/knakk/rdf](https://github.com/knakk/rdf), or bindings for an existing mature library such as [Redland](https://github.com/PhillP/golibrdf).

Let me know if you have any further questions.

**Comment by nii236** [comment]
No problem! I just preferred to use your library because you had a cool concurrency/pipeline thing going whereas the other ones were just doing it synchronously. I'll have a look at knakk's package, thanks!
